version: "3"
services:
  nginx:
    image: nginx:latest
    container_name: prod_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/wwwroot:/var/wwwroot:ro
      - ./conf/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/certs
    depends_on:
      - php
# project can be proxy_pass by nginx if you don't want it to exposed.
#    networks:
#      - default
#      - project_default
  php:
    build:
      context: ../php/7.2-fpm
      dockerfile: Dockerfile
    image: kenx/php:7.2-fpm
    container_name: prod_php
    restart: always
#    ports:
#      - "9000:9000"
    volumes:
      - ./data/wwwroot:/var/wwwroot
    env_file:
      - ./.php.env
      - ./.mysql.env
  mysql:
    image: mysql:5.7
    container_name: prod_mysql
    restart: always
    env_file:
      - ./.mysql.env
#    ports:
#      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql 
      - ./conf/mysql/my.cnf:/etc/my.cnf
  redis:
    image: redis:latest
    container_name: prod_redis
    restart: always
#    ports:
#      - "6379:6379"
    volumes:
      - ./data/redis:/data
      - ./conf/redis/redis.conf:/etc/redis.conf
    command: redis-server /etc/redis.conf
    sysctls:
      - net.core.somaxconn=512
  mongo:
    image: mongo:latest
    container_name: prod_mongo
    restart: always
#    ports:
#      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db
  memcached:
    image: memcached:latest
    container_name: prod_memcached
    restart: always
#    ports:
#      - "11211:11211"

#networks:
#  project_default:
#    external: true
