version: "3"
services:
  nginx:
    image: nginx:latest
    container_name: dev_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/wwwroot:/var/wwwroot:ro
      - ./conf/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/certs
    depends_on:
      - php
    environment:
      - TZ=Asia/Shanghai
  php:
    build:
      context: ../php/7.2-fpm-xdebug
      dockerfile: Dockerfile
    image: kenx/php:7.2-fpm-xdebug
    container_name: dev_php
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - ./data/wwwroot:/var/wwwroot
      - ./conf/php/xdebug-docke-for-mac.ini:/usr/local/etc/php/conf.d/xdebug-config.ini
    environment:
      - TZ=Asia/Shanghai
    env_file:
      - ./.php.env
      - ./.mysql.env
  mysql:
    image: mysql:5.7
    container_name: dev_mysql
    restart: always
    environment:
      - TZ=Asia/Shanghai
    env_file:
      - ./.mysql.env
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql 
  redis:
    image: redis:latest
    container_name: dev_redis
    restart: always
    sysctls:
      - net.core.somaxconn=512
    ports:
      - "6379:6379"
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./data/redis:/data
      - ./conf/redis/redis.conf:/etc/redis.conf
    command: redis-server /etc/redis.conf
  mongo:
    image: mongo:latest
    container_name: dev_mongo
    restart: always
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db
  memcached:
    image: memcached:latest
    container_name: dev_memcached
    restart: always
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "11211:11211"
  adminer:
    image: adminer:latest
    container_name: dev_adminer
    restart: always
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "8080:8080"
