FROM php:5.6-fpm

ARG SOURCE=
# https://getcomposer.org/installer
ARG COMPOSER=https://install.phpcomposer.com/installer
ARG COMPOSER_ADDR=https://packagist.phpcomposer.com
ARG XDEBUG=1

# set apt repos
RUN if [ ${SOURCE} ]; then \
		mv /etc/apt/sources.list /etc/apt/sources.list.bak; \
		{ \
    	    echo "deb http://${SOURCE}/debian/ jessie main non-free contrib"; \
        	echo "deb-src http://${SOURCE}/debian/ jessie main non-free contrib"; \
        	echo "deb http://${SOURCE}/debian-security/ jessie/updates main non-free contrib"; \
	        echo "deb-src http://${SOURCE}/debian-security/ jessie/updates main non-free contrib"; \
		} > /etc/apt/sources.list; \
		\
		cat /etc/apt/sources.list; \
	fi; \
	\
	mkdir /var/www/.composer && chown www-data:www-data /var/www/.composer
#	if [ ${SOURCE_REPLACE} ]; then \
#		sed -i "s/${SOURCE}/${SOURCE_REPLACE}/g" /etc/apt/sources.list; \
#		cat /etc/apt/sources.list; \
#	fi

RUN curl -sS ${COMPOSER} | php; \
	mv composer.phar /usr/local/bin/composer; \
	chmod +x /usr/local/bin/composer; \
	composer -V; \
	if [ ${COMPOSER_ADDR} ]; then \
		composer config -g repo.packagist composer ${COMPOSER_ADDR}; \
	fi

RUN set -ex; \
	\
	savedAptMark="$(apt-mark showmanual)"; \
	\
	apt-get update; \
	apt-get install -y \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libmcrypt-dev \
        libxml2-dev \
		libssl-dev \
		libmemcached-dev \
        libpng-dev; \
	\
    docker-php-ext-install -j$(nproc) mcrypt pdo_mysql sockets mysqli zip; \
    docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/; \
    docker-php-ext-install -j$(nproc) gd; \
	\
	pecl install igbinary-2.0.7; \
	docker-php-ext-enable igbinary; \
	pecl install mongo redis; \
	docker-php-ext-enable mongo redis; \
	if [ ${XDEBUG} ]; then \
		pecl install xdebug-2.5.5; \
		docker-php-ext-enable xdebug; \
	fi; \
	\
	pecl download memcached-2.2.0 \
	&& tar xf memcached-2.2.0.tgz \
	&& rm memcached-2.2.0.tgz \
	&& ( \
		cd memcached-2.2.0 \
		&& phpize \
		&& ./configure --enable-memcached-igbinary \
		&& make -j$(nproc) \
		&& make install \
	) \
	&& rm -r memcached-2.2.0 \
	&& docker-php-ext-enable memcached; \
	\
# reset apt-mark's "manual" list so that "purge --auto-remove" will remove all build dependencies
	apt-mark auto '.*' > /dev/null; \
	apt-mark manual $savedAptMark; \
	ldd "$(php -r 'echo ini_get("extension_dir");')"/*.so \
		| awk '/=>/ { print $3 }' \
		| sort -u \
		| xargs -r dpkg-query -S \
		| cut -d: -f1 \
		| sort -u \
		| xargs -rt apt-mark manual; \
	\
	apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false; \
	rm -rf /var/lib/apt/lists/*

# set recommended PHP.ini settings
# see https://secure.php.net/manual/en/opcache.installation.php
RUN { \
		echo 'opcache.memory_consumption=128'; \
		echo 'opcache.interned_strings_buffer=8'; \
		echo 'opcache.max_accelerated_files=4000'; \
		echo 'opcache.revalidate_freq=2'; \
		echo 'opcache.fast_shutdown=1'; \
		echo 'opcache.enable_cli=1'; \
	} > /usr/local/etc/php/conf.d/opcache-recommended.ini